### ISSUE TITLE
Error when running command

### ISSUE THREAD

**Issue by jljorden** [creditkarma/thrift-parser#71]
When I run the command 
thrift-parser --rootDir thrift --outDir thrift-json --fastFail false struct.thrift

I get this error:
internal/fs/utils.js:314
    throw err;
    ^

Error: EINVAL: invalid argument, mkdir 'C:\c:'
    at Object.mkdirSync (fs.js:1009:3)
    at createPath (C:\Users\1322919\AppData\Roaming\npm\node_modules\@creditkarma\thrift-parser\dist\main\bin\mkdir.js:17:12)
    at Object.mkdir (C:\Users\1322919\AppData\Roaming\npm\node_modules\@creditkarma\thrift-parser\dist\main\bin\mkdir.js:29:9)
    at C:\Users\1322919\AppData\Roaming\npm\node_modules\@creditkarma\thrift-parser\dist\main\bin\index.js:17:13
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\1322919\AppData\Roaming\npm\node_modules\@creditkarma\thrift-parser\dist\main\bin\index.js:11:29)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  errno: -4071,
  syscall: 'mkdir',
  code: 'EINVAL',
  path: 'C:\\c:'
}
[struct.txt](https://github.com/creditkarma/thrift-parser/files/6869768/struct.txt)
I've attached my thrift file as a txt file (thrift files aren't supported as attachments).

**Comment by elreimundo** [comment]
`Error: EINVAL: invalid argument, mkdir <directory>` appears to be a windows config issue that can be solved by updating your global `.npmrc` file (see the multitude of results at https://www.google.com/search?q=Error%3A+EINVAL%3A+invalid+argument%2C+mkdir). Do any of these help?

**Comment by jljorden** [comment]
Sadly, no. But I got around it using @creditkarma/typescript
